import React,{useEffect,useState} from 'react';
import {Alert,Modal,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import type {AppSettings} from '../types/trading';
const C={bg:'#071019',card:'#0D1A24',border:'#263847',text:'#F4F7FA',muted:'#8DA0B4',green:'#35D99A',yellow:'#F4B740'};
type Brokerage=NonNullable<AppSettings['brokerage']>;
const defaults:Brokerage={feeRate:0.001425,feeDiscount:1,regularMinFee:20,oddLotMinFee:1,stockSellTaxRate:0.003,dayTradeSellTaxRate:0.0015,oddLotThreshold:1000,configured:false};
export function BrokerageSettingsModal({visible,current,onClose,onSave}:{visible:boolean;current?:Brokerage;onClose:()=>void;onSave:(x:Brokerage)=>Promise<void>}){
 const cfg={...defaults,...(current||{})};const[discount,setDiscount]=useState(String(cfg.feeDiscount*10));const[regularMin,setRegularMin]=useState(String(cfg.regularMinFee));const[oddMin,setOddMin]=useState(String(cfg.oddLotMinFee));const[busy,setBusy]=useState(false);
 useEffect(()=>{if(visible){const x={...defaults,...(current||{})};setDiscount(String(x.feeDiscount*10));setRegularMin(String(x.regularMinFee));setOddMin(String(x.oddLotMinFee));}},[visible,current]);
 async function save(){const d=Number(discount),r=Number(regularMin),o=Number(oddMin);if(!(d>0&&d<=10)||!(r>=0)||!(o>=0)){Alert.alert('設定不正確','折數請填 0～10，最低手續費請填 0 以上。');return}setBusy(true);try{await onSave({...cfg,feeDiscount:d/10,regularMinFee:r,oddLotMinFee:o,configured:true})}finally{setBusy(false)}}
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={s.backdrop}><View style={s.card}><Text style={s.title}>交易成本設定</Text><Text style={s.note}>這份會直接影響成交後現金與淨損益，所以只設定你券商真正的規則。</Text><Text style={s.label}>手續費折數</Text><TextInput value={discount} onChangeText={setDiscount} keyboardType="decimal-pad" style={s.input}/><Text style={s.hint}>10 = 無折扣；例如 2.8 折就填 2.8</Text><Text style={s.label}>整股每筆最低手續費</Text><TextInput value={regularMin} onChangeText={setRegularMin} keyboardType="number-pad" style={s.input}/><Text style={s.label}>零股每筆最低手續費</Text><TextInput value={oddMin} onChangeText={setOddMin} keyboardType="number-pad" style={s.input}/><View style={s.fixed}><Text style={s.fixedText}>基準手續費率 0.1425%</Text><Text style={s.fixedText}>一般股票賣出證交稅 0.3%</Text><Text style={s.fixedText}>現股當沖賣出 0.15%</Text></View><View style={s.row}><TouchableOpacity disabled={busy} style={s.cancel} onPress={onClose}><Text style={s.cancelText}>取消</Text></TouchableOpacity><TouchableOpacity disabled={busy} style={s.save} onPress={save}><Text style={s.saveText}>{busy?'儲存中…':'儲存'}</Text></TouchableOpacity></View></View></View></Modal>
}
const s=StyleSheet.create({backdrop:{flex:1,backgroundColor:'rgba(0,0,0,.72)',alignItems:'center',justifyContent:'center',padding:20},card:{width:'100%',maxWidth:430,backgroundColor:C.card,borderWidth:1,borderColor:C.border,borderRadius:18,padding:16},title:{color:C.text,fontSize:22,fontWeight:'900'},note:{color:C.yellow,fontSize:12,lineHeight:18,marginTop:6,marginBottom:10},label:{color:C.muted,fontSize:12,fontWeight:'800',marginTop:8,marginBottom:5},input:{backgroundColor:C.bg,borderWidth:1,borderColor:C.border,borderRadius:10,color:C.text,fontSize:18,fontWeight:'800',paddingHorizontal:12,paddingVertical:10},hint:{color:C.muted,fontSize:11,marginTop:4},fixed:{marginTop:12,borderTopWidth:1,borderColor:C.border,paddingTop:10,gap:4},fixedText:{color:C.muted,fontSize:12},row:{flexDirection:'row',gap:8,marginTop:16},cancel:{flex:1,borderWidth:1,borderColor:C.border,borderRadius:10,padding:12,alignItems:'center'},cancelText:{color:C.muted,fontWeight:'800'},save:{flex:1,backgroundColor:C.green,borderRadius:10,padding:12,alignItems:'center'},saveText:{color:'#04100B',fontWeight:'900'}});
