import React,{useEffect,useState} from 'react';
import {ActivityIndicator,Modal,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import {claimPairing} from '../api';
import {getConnection,initializeConnection} from '../connection';

export function PairingModal({visible,onClose,onPaired}:{visible:boolean;onClose:()=>void;onPaired:()=>Promise<void>|void}){
 const [url,setUrl]=useState('');const [code,setCode]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{if(!visible)return;initializeConnection().then(()=>setUrl(getConnection().apiUrl)).catch(()=>{});setCode('');setError('')},[visible]);
 const pair=async()=>{setBusy(true);setError('');try{await claimPairing(url,code);await onPaired();onClose()}catch(e:any){setError(e?.message||'配對失敗')}finally{setBusy(false)}};
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><View style={s.backdrop}><View style={s.card}><Text style={s.title}>連接你的電腦</Text><Text style={s.help}>在電腦執行「手機配對」後，這裡只要輸入電腦位址和 6 位配對碼。token 會安全存進手機，不用手打長字串。</Text><Text style={s.label}>Backend 位址</Text><TextInput style={s.input} value={url} onChangeText={setUrl} autoCapitalize="none" autoCorrect={false} placeholder="192.168.1.23:8787" placeholderTextColor="#64788B"/><Text style={s.label}>6 位配對碼</Text><TextInput style={[s.input,{fontSize:22,letterSpacing:5,textAlign:'center'}]} value={code} onChangeText={x=>setCode(x.replace(/\D/g,'').slice(0,6))} keyboardType="number-pad" maxLength={6} placeholder="123456" placeholderTextColor="#64788B"/>{error?<Text style={s.error}>{error}</Text>:null}<View style={s.row}><TouchableOpacity style={s.cancel} onPress={onClose} disabled={busy}><Text style={s.cancelText}>取消</Text></TouchableOpacity><TouchableOpacity style={[s.ok,(busy||code.length!==6)&&{opacity:.5}]} onPress={pair} disabled={busy||code.length!==6}>{busy?<ActivityIndicator color="#07110D"/>:<Text style={s.okText}>配對</Text>}</TouchableOpacity></View></View></View></Modal>
}
const s=StyleSheet.create({backdrop:{flex:1,backgroundColor:'rgba(0,0,0,.76)',alignItems:'center',justifyContent:'center',padding:20},card:{width:'100%',maxWidth:430,backgroundColor:'#0B1620',borderWidth:1,borderColor:'#20303E',borderRadius:18,padding:18},title:{color:'#F4F7FA',fontSize:20,fontWeight:'900'},help:{color:'#8DA0B4',fontSize:13,lineHeight:19,marginTop:8,marginBottom:10},label:{color:'#8DA0B4',fontSize:12,fontWeight:'800',marginTop:10,marginBottom:5},input:{borderWidth:1,borderColor:'#2A3A49',borderRadius:10,paddingHorizontal:12,paddingVertical:11,color:'#F4F7FA',backgroundColor:'#08121A'},error:{color:'#FF5B67',fontSize:12,marginTop:10},row:{flexDirection:'row',gap:10,marginTop:18},cancel:{flex:1,borderWidth:1,borderColor:'#2A3A49',borderRadius:10,paddingVertical:11,alignItems:'center'},cancelText:{color:'#F4F7FA',fontWeight:'800'},ok:{flex:1,backgroundColor:'#35D99A',borderRadius:10,paddingVertical:11,alignItems:'center'},okText:{color:'#07110D',fontWeight:'900'}});
