import React,{useEffect,useState} from 'react';
import {ActivityIndicator,Modal,Pressable,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import {parseQuickTrade,previewTrade,recordTrade} from '../api';
const C={bg:'#071019',card:'#0D1A24',border:'#263847',text:'#F4F7FA',muted:'#8DA0B4',green:'#35D99A',red:'#FF5B67',yellow:'#F4B740'};
function localParse(text:string){const m=String(text).trim().match(/^(\d{4,6})\s+(\d+(?:\.\d+)?)\s+([+-]\d+)$/);if(!m)return null;const signed=Number(m[3]);return{symbol:m[1],name:m[1],price:Number(m[2]),quantity:Math.abs(signed),side:signed>0?'BUY':'SELL'};}
export function QuickTradeModal({visible,onClose,onDone}:{visible:boolean;onClose:()=>void;onDone:()=>Promise<void>}){
 const[text,setText]=useState(''),[parsed,setParsed]=useState<any>(null),[quote,setQuote]=useState<any>(null),[busy,setBusy]=useState(false),[err,setErr]=useState('');
 useEffect(()=>{if(visible){setText('');setParsed(null);setQuote(null);setErr('')}},[visible]);
 async function prepare(){setBusy(true);setErr('');try{const local=localParse(text);const p=local||await parseQuickTrade(text);setParsed(p);try{setQuote(await previewTrade(p))}catch{setQuote(null)}}catch(e:any){setParsed(null);setQuote(null);setErr(e?.message||'格式需為：股票代號 價格 +股數 / -股數')}finally{setBusy(false)}}
 async function confirm(){if(!parsed)return;setBusy(true);setErr('');try{await recordTrade(parsed);onClose();await onDone()}catch(e:any){setErr(e?.message||'尚未提交，請確認網路後重試')}finally{setBusy(false)}}
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><Pressable style={s.backdrop} onPress={onClose}/><View style={s.sheet}><Text style={s.title}>快速記成交</Text><Text style={s.hint}>例如：1714 16.65 +1000（代號格式可在電腦離線時使用）</Text><TextInput autoFocus value={text} onChangeText={x=>{setText(x);setParsed(null);setQuote(null)}} onSubmitEditing={prepare} placeholder="股票代號 價格 +股數 / -股數" placeholderTextColor={C.muted} style={s.input}/>{err?<Text style={s.err}>{err}</Text>:null}{parsed?<View style={s.quote}><Text style={s.quoteTitle}>{parsed.name} {parsed.symbol}｜{parsed.side==='BUY'?'買進':'賣出'} {parsed.quantity} 股 @ {parsed.price}</Text>{quote?<><Text style={s.row}>成交金額　NT$ {Number(quote.gross).toLocaleString()}</Text><Text style={s.row}>手續費　NT$ {quote.brokerFee}</Text>{parsed.side==='SELL'?<Text style={s.row}>證交稅　NT$ {quote.transactionTax}</Text>:null}</>:<Text style={[s.row,{color:C.yellow}]}>電腦離線：稍後由本機 Ledger 驗證成本與餘額</Text>}</View>:null}<TouchableOpacity disabled={busy} style={parsed?s.confirm:s.prepare} onPress={parsed?confirm:prepare}>{busy?<ActivityIndicator color={parsed?'#04100B':C.green}/>:<Text style={parsed?s.confirmText:s.prepareText}>{parsed?'提交已成交紀錄':'檢查格式'}</Text>}</TouchableOpacity></View></Modal>;
}
const s=StyleSheet.create({backdrop:{...StyleSheet.absoluteFill,backgroundColor:'rgba(0,0,0,.65)'},sheet:{position:'absolute',left:14,right:14,bottom:24,backgroundColor:C.card,borderRadius:20,borderWidth:1,borderColor:C.border,padding:18},title:{fontSize:21,color:C.text,fontWeight:'900'},hint:{color:C.muted,fontSize:12,marginTop:5},input:{backgroundColor:C.bg,borderWidth:1,borderColor:C.border,borderRadius:12,color:C.text,fontSize:18,fontWeight:'800',paddingHorizontal:12,paddingVertical:11,marginTop:12},err:{color:C.red,marginTop:8},quote:{borderWidth:1,borderColor:C.border,borderRadius:12,padding:11,marginTop:12,gap:4},quoteTitle:{color:C.text,fontWeight:'900',fontSize:15},row:{color:C.muted,fontSize:13},prepare:{borderWidth:1,borderColor:C.green,borderRadius:12,padding:13,alignItems:'center',marginTop:14},prepareText:{color:C.green,fontWeight:'900'},confirm:{backgroundColor:C.green,borderRadius:12,padding:13,alignItems:'center',marginTop:14},confirmText:{color:'#04100B',fontWeight:'900'}});
