import React,{useEffect,useState} from 'react';
import {ActivityIndicator,Modal,Pressable,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import type {StockSnapshot,TradeSide} from '../types/trading';
import {previewTrade} from '../api';
const C={bg:'#071019',card:'#0D1A24',border:'#263847',text:'#F4F7FA',muted:'#8DA0B4',green:'#35D99A',red:'#FF5B67',yellow:'#F4B740'};
export function TradeModal({stock,visible,onClose,onSubmit}:{stock:StockSnapshot;visible:boolean;onClose:()=>void;onSubmit:(x:{side:TradeSide;quantity:number;price:number;dayTrade?:boolean})=>Promise<void>}){
 const[side,setSide]=useState<TradeSide>('BUY'),[price,setPrice]=useState(String(stock.price)),[qty,setQty]=useState('100'),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[quote,setQuote]=useState<any>(null),[dayTrade,setDayTrade]=useState(false);
 useEffect(()=>{if(visible){setPrice(String(stock.price));setErr('');setQuote(null);setDayTrade(false)}},[visible,stock.price]);
 useEffect(()=>{if(!visible||!(Number(qty)>0)||!(Number(price)>0)){setQuote(null);return}const id=setTimeout(()=>previewTrade({symbol:stock.symbol,name:stock.name,side,quantity:Number(qty),price:Number(price),dayTrade:side==='SELL'&&dayTrade}).then(setQuote).catch(()=>setQuote(null)),250);return()=>clearTimeout(id)},[visible,stock.symbol,stock.name,side,qty,price,dayTrade]);
 async function submit(){setBusy(true);setErr('');try{await onSubmit({side,quantity:Number(qty),price:Number(price),dayTrade:side==='SELL'&&dayTrade});onClose()}catch(e:any){setErr(e.message||'尚未提交，請重試')}finally{setBusy(false)}}
 const valid=Number(qty)>0&&Number(price)>0;
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><Pressable style={m.backdrop} onPress={onClose}/><View style={m.sheet}><Text style={m.title}>記錄成交｜{stock.name} {stock.symbol}</Text><View style={m.row}><TouchableOpacity style={[m.choice,side==='BUY'&&{borderColor:C.red}]} onPress={()=>setSide('BUY')}><Text style={{color:side==='BUY'?C.red:C.muted,fontWeight:'900'}}>買進</Text></TouchableOpacity><TouchableOpacity style={[m.choice,side==='SELL'&&{borderColor:C.green}]} onPress={()=>setSide('SELL')}><Text style={{color:side==='SELL'?C.green:C.muted,fontWeight:'900'}}>賣出</Text></TouchableOpacity></View><Text style={m.label}>成交價</Text><TextInput value={price} onChangeText={setPrice} keyboardType="decimal-pad" style={m.input}/><Text style={m.label}>股數</Text><TextInput value={qty} onChangeText={setQty} keyboardType="number-pad" style={m.input}/>{side==='SELL'?<TouchableOpacity style={m.dayTrade} onPress={()=>setDayTrade(x=>!x)}><Text style={{color:dayTrade?C.yellow:C.muted,fontWeight:'800'}}>{dayTrade?'☑':'☐'} 現股當沖賣出</Text></TouchableOpacity>:null}{quote?<View style={m.preview}><Text style={m.previewText}>成交金額 NT$ {Number(quote.gross).toLocaleString()}　手續費 {quote.brokerFee}{side==='SELL'?`　稅 ${quote.transactionTax}`:''}</Text><Text style={m.previewText}>成交後現金 NT$ {Number(quote.afterCash).toLocaleString()}</Text></View>:<Text style={m.offline}>電腦離線：可先提交，稍後由本機 Ledger 驗證</Text>}{err?<Text style={m.err}>{err}</Text>:null}<TouchableOpacity disabled={busy||!valid} style={[m.submit,!valid&&{opacity:.45}]} onPress={submit}>{busy?<ActivityIndicator color="#04100B"/>:<Text style={m.submitText}>提交已成交紀錄</Text>}</TouchableOpacity><Text style={m.note}>只記錄券商已成交的操作，不會替你下單。</Text></View></Modal>;
}
const m=StyleSheet.create({backdrop:{...StyleSheet.absoluteFill,backgroundColor:'rgba(0,0,0,.65)'},sheet:{position:'absolute',left:14,right:14,bottom:24,backgroundColor:C.card,borderRadius:20,borderWidth:1,borderColor:C.border,padding:18},title:{fontSize:20,color:C.text,fontWeight:'900',marginBottom:14},row:{flexDirection:'row',gap:10,marginBottom:12},choice:{flex:1,padding:12,borderWidth:1,borderColor:C.border,borderRadius:12,alignItems:'center'},label:{color:C.muted,fontSize:12,fontWeight:'800',marginTop:8,marginBottom:5},input:{backgroundColor:C.bg,borderWidth:1,borderColor:C.border,borderRadius:12,color:C.text,fontSize:20,fontWeight:'800',paddingHorizontal:12,paddingVertical:10},dayTrade:{paddingVertical:9},preview:{borderTopWidth:1,borderColor:C.border,marginTop:6,paddingTop:9,gap:3},previewText:{color:C.muted,fontSize:12},offline:{color:C.yellow,fontSize:12,marginTop:10},err:{color:C.red,marginTop:8},submit:{marginTop:12,backgroundColor:C.green,borderRadius:12,padding:14,alignItems:'center'},submitText:{color:'#04100B',fontWeight:'900'},note:{color:C.muted,fontSize:11,marginTop:10,lineHeight:16}});
