import test from 'node:test';import assert from 'node:assert/strict';
import {ledgerMutationRoutes} from './worker.mjs';
const norm=s=>s.replace(/\s+/g,' ').trim();
class DB{constructor(){this.devices=new Map();this.rows=new Map()}prepare(sql){const db=this,args=[];return{bind(...x){args.push(...x);return this},async run(){const q=norm(sql);if(q.startsWith('INSERT INTO ledger_devices')){db.devices.set(args[0],{device_id:args[0],token_hash:args[1],enabled:1});return{}}if(q.startsWith('INSERT INTO ledger_mutations')){if([...db.rows.values()].some(r=>r.device_id===args[1]&&(r.idempotency_key===args[3]||r.client_sequence===args[2])))throw new Error('unique');db.rows.set(args[0],{mutation_id:args[0],device_id:args[1],client_sequence:args[2],idempotency_key:args[3],schema_version:args[4],mutation_type:args[5],payload:args[6],status:'pending',created_at:args[7],applied_at:null,apply_result:null,rejection_reason:null});return{}}if(q.startsWith('UPDATE ledger_mutations')){const r=db.rows.get(args[4]);if(r&&r.status==='pending')Object.assign(r,{status:args[0],applied_at:args[1],apply_result:args[2],rejection_reason:args[3]});return{}}throw Error(q)},async first(){const q=norm(sql);if(q.includes('FROM ledger_devices'))return db.devices.get(args[0])||null;if(q.includes('WHERE mutation_id=? OR'))return db.rows.get(args[0])||[...db.rows.values()].find(r=>r.device_id===args[1]&&r.idempotency_key===args[2])||null;if(q.includes('WHERE mutation_id=?'))return db.rows.get(args[0])||null;throw Error(q)},async all(){const q=norm(sql);if(q.includes('WHERE status=?'))return{results:[...db.rows.values()].filter(r=>r.status===args[0])};if(q.includes('WHERE device_id=?'))return{results:[...db.rows.values()].filter(r=>r.device_id===args[0])};throw Error(q)}}}}
const key='c'.repeat(64),token='d'.repeat(64),deviceId='dev_test',env={DB:new DB(),TRADING_API_KEY:key};
async function route(path,init={}){const req=new Request(`https://x.test${path}`,init),u=new URL(req.url);return ledgerMutationRoutes(req,env,u,u.pathname)}
test('Cloud device registration requires privileged auth',async()=>{let r=await route('/v1/ledger/devices',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({deviceId,token})});assert.equal(r.status,401);r=await route('/v1/ledger/devices',{method:'POST',headers:{'content-type':'application/json','x-api-key':key},body:JSON.stringify({deviceId,token})});assert.equal(r.status,201)});
test('mobile queues pending mutation and retry is idempotent after lost response',async()=>{const body=JSON.stringify({mutationId:'lm_cloud_12345678',idempotencyKey:'same',clientSequence:1,schemaVersion:1,mutationType:'POSITION_ADD',payload:{symbol:'1714',quantity:1000,averageCost:16.65}}),init={method:'POST',headers:{'content-type':'application/json','x-device-id':deviceId,'x-device-token':token},body};let r=await route('/v1/ledger/mutations',init);assert.equal(r.status,202);r=await route('/v1/ledger/mutations',init);assert.equal(r.status,200);assert.equal(env.DB.rows.size,1);assert.equal((await r.json()).mutation.status,'pending')});
test('pending mutation moves to applied and remains terminal on duplicate ack',async()=>{const h={'content-type':'application/json','x-api-key':key};let r=await route('/v1/ledger/mutations/lm_cloud_12345678',{method:'PATCH',headers:h,body:JSON.stringify({status:'applied',result:{ok:true}})});assert.equal((await r.json()).status,'applied');r=await route('/v1/ledger/mutations/lm_cloud_12345678',{method:'PATCH',headers:h,body:JSON.stringify({status:'rejected',reason:'late'})});assert.equal((await r.json()).status,'applied')});
test('GPT bearer cannot submit a Ledger mutation',async()=>{const r=await route('/v1/ledger/mutations',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token},body:'{}'});assert.equal(r.status,401)});
