import { McpServer } from '@modelcontextprotocol/server';
import * as z from 'zod/v4';
const API=process.env.TRADING_API_URL||'http://localhost:8787'; const KEY=process.env.TRADING_API_KEY;
async function api(path:string,init:RequestInit={}){const r=await fetch(`${API}${path}`,{...init,headers:{'content-type':'application/json',...(KEY?{'x-api-key':KEY}:{}),...(init.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.json();}
const text=(x:unknown)=>({content:[{type:'text' as const,text:JSON.stringify(x,null,2)}],structuredContent:x});
export function createTradingMcp(){
 const server=new McpServer({name:'eason-trading',version:'0.3.18'},{capabilities:{tools:{}}});
 server.registerTool('get_founder_brief',{description:'Read the authoritative current trading context: portfolio, real positions, rolling setup pool, playbooks, recent executed trades, alerts, latest close package and audit changes.',annotations:{readOnlyHint:true,openWorldHint:false}},async()=>text(await api('/v1/founder-brief')));
 server.registerTool('get_portfolio',{description:'Read current portfolio totals and real holdings.',annotations:{readOnlyHint:true,openWorldHint:false}},async()=>text({portfolio:await api('/v1/portfolio'),positions:await api('/v1/positions')}));
 server.registerTool('get_watchlist',{description:'Read the persistent radar/watchlist. Stocks persist across days instead of being reset as a daily list.',annotations:{readOnlyHint:true,openWorldHint:false}},async()=>text(await api('/v1/watchlist')));
 server.registerTool('get_rolling_setup_pool',{description:'Read the permanent multi-day Setup Cards for active candidates. Use this for nightly selection so old setups are re-ranked against new discoveries instead of being forgotten.',annotations:{readOnlyHint:true,openWorldHint:false}},async()=>text(await api('/v1/setups?active=true')));
 server.registerTool('get_stock_context',{description:'Read position, current market snapshot, watch state, persistent Setup Card, user hypotheses, playbook, executed trades, trigger history and audit history for one stock.',annotations:{readOnlyHint:true,openWorldHint:false},inputSchema:z.object({symbol:z.string().min(1)})},async({symbol})=>text(await api(`/v1/stocks/${encodeURIComponent(symbol)}/context`)));
 server.registerTool('get_reviews',{description:'Read recorded trade/model reviews and lessons.',annotations:{readOnlyHint:true,openWorldHint:false}},async()=>text(await api('/v1/reviews')));
 server.registerTool('get_alerts',{description:'Read recent deduplicated trading radar alerts.',annotations:{readOnlyHint:true,openWorldHint:false}},async()=>text(await api('/v1/alerts')));
 server.registerTool('get_close_package',{description:'Read the latest automatically prepared close package. The package puts actual executed buys/sells first, then closing positions, setup changes, triggers and the rolling pool for nightly review.',annotations:{readOnlyHint:true,openWorldHint:false}},async()=>text(await api('/v1/close-packages/latest')));
 server.registerTool('get_handoff',{description:'Resolve an App-to-ChatGPT handoff ID such as “#ho_...”. Use this immediately when the user arrives from the stock app with a trigger, close-review, or nightly-selection handoff; it expands authoritative structured market data so screenshots are unnecessary for normal price/volume/K-line review.',annotations:{readOnlyHint:true,openWorldHint:false},inputSchema:z.object({handoffId:z.string().min(1)})},async({handoffId})=>{const id=handoffId.replace(/^#/,'');return text(await api(`/v1/handoffs/${encodeURIComponent(id)}`))});
 server.registerTool('acknowledge_handoff',{description:'Mark a handoff as acknowledged after its context has been read. This does not change positions, playbooks or triggers.',annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false},inputSchema:z.object({handoffId:z.string().min(1)})},async({handoffId})=>{const id=handoffId.replace(/^#/,'');return text(await api(`/v1/handoffs/${encodeURIComponent(id)}/ack`,{method:'PATCH',headers:{'x-source':'chatgpt'}}))});

 server.registerTool('update_playbook',{description:'Update strategy/watch price fields only. It never edits the executed-trade ledger. Setup lifecycle, selection validity and entry quality belong in update_setup_status.',annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false},inputSchema:z.object({symbol:z.string(),rating:z.enum(['A','A-','B+','B','B-']).optional(),state:z.enum(['NEW','WATCH','TRIGGERED','INVALID']).optional(),priority:z.number().min(0).max(100).optional(),goodZone:z.tuple([z.number(),z.number()]).optional(),breakout:z.number().optional(),invalid:z.number().optional(),target1:z.number().optional(),target2:z.number().optional(),maxEntry:z.number().optional(),summary:z.string().optional(),nextStep:z.string().optional()})},async({symbol,...patch})=>text(await api(`/v1/playbooks/${encodeURIComponent(symbol)}`,{method:'PATCH',headers:{'x-source':'chatgpt'},body:JSON.stringify(patch)})));
 server.registerTool('update_setup_status',{description:'Update the persistent Setup Card after evidence changes. Use stage for the multi-day lifecycle; selectionValidity answers whether the stock-selection thesis was right, while entryOpportunity separately answers whether there was a good buy point. Every stage change needs a concrete reason.',annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false},inputSchema:z.object({symbol:z.string(),stage:z.enum(['NEW_DISCOVERY','WAIT_TRIGGER','TRIGGERED_NO_ENTRY','WAIT_PULLBACK','READY','RECONFIRM','LOW_PRIORITY','POSITION_MANAGEMENT','CLOSED_POSITION','INVALIDATED','EXPIRED','ARCHIVED']).optional(),setupType:z.string().optional(),originalThesis:z.string().optional(),selectionValidity:z.enum(['UNREVIEWED','VALIDATED','PARTIAL','FAILED']).optional(),entryOpportunity:z.enum(['WAITING','GOOD','MARGINAL','BAD','MISSED','NOT_APPLICABLE']).optional(),statusReason:z.string().optional(),removalReason:z.string().optional(),removalReasonCode:z.string().optional()})},async({symbol,...patch})=>text(await api(`/v1/setups/${encodeURIComponent(symbol)}`,{method:'PATCH',headers:{'x-source':'chatgpt'},body:JSON.stringify(patch)})));
 server.registerTool('record_user_hypothesis',{description:'Store a user trading hypothesis separately from market evidence. New hypotheses always start UNCONFIRMED and must not by themselves change the playbook or setup validity.',annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false},inputSchema:z.object({symbol:z.string(),text:z.string().min(1),name:z.string().optional()})},async(input)=>text(await api('/v1/hypotheses',{method:'POST',headers:{'x-source':'user'},body:JSON.stringify(input)})));
 server.registerTool('update_hypothesis',{description:'Update an existing hypothesis only after evidence supports, rejects or expires it.',annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false},inputSchema:z.object({id:z.string(),status:z.enum(['UNCONFIRMED','SUPPORTED','REJECTED','EXPIRED']),evidence:z.array(z.string()).optional()})},async({id,...patch})=>text(await api(`/v1/hypotheses/${encodeURIComponent(id)}`,{method:'PATCH',headers:{'x-source':'chatgpt'},body:JSON.stringify(patch)})));
 server.registerTool('add_watch',{description:'Add or reactivate a stock in the persistent rolling radar after analysis identifies it as worth following beyond a single day.',annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false},inputSchema:z.object({symbol:z.string(),name:z.string().optional(),rating:z.enum(['A','A-','B+','B','B-']).optional(),priority:z.number().min(0).max(100).optional(),setupType:z.string().optional(),originalThesis:z.string().optional()})},async(input)=>text(await api('/v1/watchlist',{method:'POST',headers:{'x-source':'chatgpt'},body:JSON.stringify(input)})));
 server.registerTool('record_review',{description:'Persist a completed trade/model review after analysis. This writes review evidence only and never changes holdings or cash.',annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false},inputSchema:z.object({symbol:z.string(),name:z.string().optional(),thesis:z.string().optional(),result:z.string().optional(),pnlPct:z.number().optional(),mfe:z.number().optional(),mae:z.number().optional(),followedPlan:z.boolean().optional(),lesson:z.string().optional(),tags:z.array(z.string()).optional()})},async(input)=>text(await api('/v1/reviews',{method:'POST',headers:{'x-source':'chatgpt'},body:JSON.stringify(input)})));

 server.registerTool('list_pending_review_triggers',{description:'Read armed GPT review conditions that the backend is monitoring on the user’s behalf.',annotations:{readOnlyHint:true,openWorldHint:false}},async()=>text(await api('/v1/review-triggers?status=ARMED')));
 server.registerTool('create_review_trigger',{description:'Create a structured condition only when the conversation has reached a clear “when X happens, come back for GPT review” conclusion. This never trades. It only monitors and notifies the user.',annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false},inputSchema:z.object({symbol:z.string(),label:z.string().optional(),conditions:z.object({all:z.array(z.object({field:z.enum(['price','rvol','vwap','high','low','changePct']),op:z.enum(['>=','>','<=','<','==']),value:z.number()})).min(1)}),expiresAt:z.string().optional()})},async(input)=>text(await api('/v1/review-triggers',{method:'POST',headers:{'x-source':'chatgpt'},body:JSON.stringify(input)})));
 server.registerTool('cancel_review_trigger',{description:'Cancel an armed GPT review condition when the conversation replaces it with a newer condition or the setup is no longer relevant.',annotations:{readOnlyHint:false,destructiveHint:true,idempotentHint:true,openWorldHint:false},inputSchema:z.object({id:z.string()})},async({id})=>text(await api(`/v1/review-triggers/${encodeURIComponent(id)}`,{method:'DELETE',headers:{'x-source':'chatgpt'}})));
 server.registerTool('get_trigger_events',{description:'Read recent fired GPT review events, optionally for one stock. Use this when the user says a monitored condition “hit” or “touched”.',annotations:{readOnlyHint:true,openWorldHint:false},inputSchema:z.object({symbol:z.string().optional()})},async({symbol})=>text(await api(`/v1/trigger-events${symbol?`?symbol=${encodeURIComponent(symbol)}`:''}`)));
 server.registerTool('get_trigger_snapshot',{description:'Read the frozen data-only market snapshot captured at the exact time a GPT review condition fired: raw 1m/5m/daily OHLCV, market/VWAP/RVOL, playbook, Setup Card, user hypotheses and position context. No generated chart image is used.',annotations:{readOnlyHint:true,openWorldHint:false},inputSchema:z.object({snapshotId:z.string()})},async({snapshotId})=>text(await api(`/v1/trigger-snapshots/${encodeURIComponent(snapshotId)}`)));

 server.registerTool('drop_watch',{description:'Archive a non-held stock from active radar. A concrete reason is mandatory so a candidate can never silently disappear; the permanent Setup Card and removal reason remain for later review.',annotations:{readOnlyHint:false,destructiveHint:true,idempotentHint:false,openWorldHint:false},inputSchema:z.object({symbol:z.string(),reasonCode:z.enum(['INVALIDATED','THESIS_BROKEN','EXPIRED','LOW_EFFICIENCY','MANUAL']),reason:z.string().min(1)})},async({symbol,...input})=>text(await api(`/v1/watchlist/${encodeURIComponent(symbol)}`,{method:'DELETE',headers:{'x-source':'chatgpt'},body:JSON.stringify(input)})));
 return server;
}
